(define (problem strips-grid-y-2)
(:domain grid)
(:objects test_object test0-0 test0-1 test0-2 test0-3 test0-4 test0-5 key0)
(:init (open test0-0)
(open test0-1)
(open test0-2)
(locked test0-3)
(lock-shape test0-3 triangle)
(locked test0-4)
(lock-shape test0-4 triangle)
(locked test0-5)
(lock-shape test0-5 triangle)
(arm-empty )
(at-robot node5-5)
)
(:goal (at key8 node3-2))
)