
(* The purpose of this test is to make sure the parser makes a correct ast for a given input *)

open Alcotest
open Ast

(* Helper function: parse string s to AST *)
let parse_program_string s =
  (* Create tokens from string s *)
  let lexbuf = Lexing.from_string s in
  (* Parser.prog is the parser-functionen, generated by Menhir, which starts from startrule prog *)
  (* Lexer.token is the lexer-function, which reads from lexbuf and gives the parser the next tokens *)
  Parser.prog Lexer.token lexbuf

(* test for :grid 6 6 *)
let test_grid_prog () =

  (* Define input *)
  let input = "(define (problem test_problem)
                   (:domain test_domain)
                   (:objects :grid 6 6 triangle diamond key0)
                   (:init)
                   (:goal (dummy)))" in

  (* Parse input to ast via helper function *)
  let ast = parse_program_string input in

  (* Match ast.defs because startsymbol (prog) generates defs-node which contains all <definitions> *)
  match ast.defs with
  (* If match with ProblemDef...  use alcotest check *)
  | ProblemDef { objects = GridAndObjects (rows, cols, objs); _ } ->
      check int "rows match" 6 rows; (* 6 is the expected number of rows *)
      check int "cols match" 6 cols;
      check (list string) "objects match" ["triangle"; "diamond"; "key0"] objs
  | _ -> fail "Expected ProblemDef with GridAndObjects"

(* test suite *)
let () =
  Alcotest.run "Parser tests" [
    "problem parsing", [
      Alcotest.test_case "parse :grid 6 6 in prog" `Quick test_grid_prog;
    ]
  ]